- name: Remove any existing Go installation
  ansible.builtin.file:
    path: "{{ go_root }}"
    state: absent
  tags:
  - install
  - go

- name: Download Go binary
  ansible.builtin.get_url:
    url: "https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    mode: '0755'
  tags:
  - install
  - go

- name: Extract Go binary archive
  ansible.builtin.unarchive:
    src: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "/usr/local"
    creates: "{{ go_root }}/bin/go"
    extra_opts: [--strip-components=1]
    remote_src: yes
  tags:
  - install
  - go

- name: Set Go environment variables
  ansible.builtin.lineinfile:
    path: /etc/profile.d/goenv.sh
    create: yes
    line: "{{ item }}"
  with_items:
    - 'export GOROOT={{ go_root }}'
    - 'export GOPATH=$HOME/go'
    - 'export PATH=$PATH:$GOROOT/bin:$GOPATH/bin'
  mode: '0644'
  tags:
  - install
  - go
