- name: Install Visual Studio Code
  become: yes
  tags:
    - install
    - teams
  
- name: Uninstall VSCode if installed
  ansible.builtin.apt:
    name: code
    state: absent
  tags:
    - install
    - vscode

- name: Import the Microsoft GPG key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  tags:
    - install
    - vscode

- name: Add the VSCode repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
    state: present
  tags:
    - install
    - vscode

- name: Install VSCode
  ansible.builtin.apt:
    name: code
    state: present
    update_cache: yes
  tags:
    - install
    - vscode
